
display_url: "https://hassanpromo.netlify.com"

backend:
  name: git-gateway

media_folder: "content/media"
public_folder: "media"

collections:

  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - file: "content/_index.md"
        label: "Page d'accueil"
        name: "home"
        fields:
          - label: "Slides"
            name: "slides"
            widget: "list"
            fields:
              - { label: "Image (Taille minimum recommendée: 1920x700)", name: "image", widget: "image" }
          - { label: "Présentation", name: "body", widget: "markdown" }
          - { label: "Emplacement GPS du Siège Social", name: "localisation", widget: "string" }

      - file: "content/contact/_index.md"
        label: "Contact"
        name: "Contact"
        editor:
          preview: false
        fields:
          - { label: "Téléphone", name: "phone", widget: "string", required: true }
          - { label: "Adresse du Siége Social", name: "address", widget: "string" }
          - { label: "E-mail", name: "email", widget: "string" }
          - { label: "Lien page Facebook", name: "facebook", widget: "string" }
          - { label: "Lien Page Youtube", name: "youtube", widget: "string" }

  - name: "project"
    label: "Projet"
    folder: "content/project"
    editor:
      preview: false
    fields:
      - { label: "Titre", name: "title", widget: "string", required: true }
      - { label: "Image Principale (Taille minimum recommendée: 1000x500)", name: "image", widget: "image", required: true }
      - { label: "Petite présentation pour la page d'accueil", name: "texte_intro", widget: "text", required: true }
      - { label: "Présentation Détaillée", name: "body", widget: "markdown", required: true }
      - { label: "Achevé", name: "termine", widget: "boolean" }
      - { label: "Adresse du Projet", name: "address", widget: "string", required: true }
      - { label: "Emplacement GPS du Projet", name: "localisation", widget: "string", required: true }
      - { label: "Détails Appartements", name: "intro_appartements", widget: "text" }
      - { label: "Type", name: "type", widget: "hidden", default: "project"}
      - label: "Caracteristiques"
        name: "specs"
        widget: "list"
        fields:
          - { label: "Caracteristique", name: "spec", widget: "string" }
      - label: "Plans"
        name: "plans"
        widget: "list"
        fields:
          - { label: "Image (Taille minimum recommendée: 1280x720)", name: "image", widget: "image" }
          - { label: "Titre", name: "title", widget: "string" }
        - label: "Gallerie de photos"
        name: "galerie"
        widget: "list"
        fields:
          - { label: "Image (Taille minimum recommendée: 1280x720)", name: "image", widget: "image" }
      - label: "Avancements"
        name: "avancement"
        widget: "list"
        fields:
          - { label: "Image (Taille minimum recommendée: 1280x720)", name: "image", widget: "image" }

